apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtenantworkloads.example.upbound.io
spec:
  group: example.upbound.io
  names:
    kind: XTenantWorkload
    plural: xtenantworkloads
  claimNames:
    kind: TenantWorkload
    plural: tenantworkloads
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        description: TenantWorkloads define instances of the application running within a platform Zone
        type: object
        properties:
          spec:
            description: Specification of the desired state of the Composite Resource
            type: object
            properties:
              parameters:
                description: Configuration parameters for XTenantWorkloads
                type: object
                properties:
                  id:
                    type: string
                    description: TenantWorkload ID used throughout the platform
          status:
            description: Most recently observed state of the Composite Resource