apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.example.upbound.io
spec:
  group: example.upbound.io
  names:
    kind: XCluster
    plural: xclusters
  claimNames:
    kind: Cluster
    plural: clusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Clusters deploy AKS clusters into Zones
        type: object
        properties:
          spec:
            description: Specification of the desired state of the Composite Resource
            type: object
            properties:
              parameters:
                description: Configuration parameters for XClusters
                type: object
                properties:
                  id:
                    type: string
                    description: Cluster ID used throughout the platform
          status:
            description: Most recently observed state of the Composite Resource